/** text reducers actions */
export const SET_TYPE_FORM = 'SET_TYPE_FORM';
export const SET_MODAL_VISIBLE = 'SET_MODAL_VISIBLE';
/** hospitals */
export const LIST_HOSPITAL = 'LIST_HOSPITAL';
export const TOTAL_LIST_HOSPITAL = 'TOTAL_LIST_HOSPITAL';
export const LIST_HOSPITAL_LOADING = 'LIST_HOSPITAL_LOADING';
export const SAVE_HOSPITAL_LOADING = 'SAVE_HOSPITAL_LOADING';
export const SELECTED_HOSPITAL = 'SELECTED_HOSPITAL';

/** doctors reducers */
export const LIST_DOCTORS = 'LIST_DOCTORS';
export const TOTAL_LIST_DOCTORS = 'TOTAL_LIST_DOCTORS';
export const LIST_DOCTORS_LOADING = 'LIST_DOCTORS_LOADING';
export const SAVE_DOCTORS_LOADING = 'SAVE_DOCTORS_LOADING';
export const SELECTED_DOCTOR = 'SELECTED_DOCTOR';

/** patients */
export const LIST_PATIENTS_LOADING = 'LIST_PATIENTS_LOADING';
export const SAVE_PATIENTS_LOADING = 'SAVE_PATIENTS_LOADING';
export const LIST_PATIENTS = 'LIST_PATIENTS';
export const TOTAL_LIST_PATIENTS = 'TOTAL_LIST_PATIENTS';
export const SELECTED_PATIENT = 'SELECTED_PATIENT';

export const ADD_FORM_TEXT = 'ADD_FORM_TEXT';
export const EDIT_FORM_TEXT = 'EDIT_FORM_TEXT';
export const DELETE_FORM_TEXT = 'DELETE_FORM_TEXT';
export const DETAILS_FORM_TEXT = 'DETAILS_FORM_TEXT';

/** validator text */
export const REQUIRED_FIELD = 'Este campo es obligatorio.';

/** pagination */
export const SET_PAGINATION_PAGE = 'SET_PAGINATION_PAGE';
export const SET_PAGINATION_LIMIT = 'SET_PAGINATION_LIMIT';
