/** text reducers actions */
export const SET_ROLES = 'SET_ROLES';
export const SET_MODAL_VISIBLE = 'SET_MODAL_VISIBLE';
export const UNSUSBCRIBE_FROM_ALL = 'UNSUSBCRIBE_FROM_ALL';
/** hospitals */
export const LIST_HOSPITAL = 'LIST_HOSPITAL';
export const TOTAL_LIST_HOSPITAL = 'TOTAL_LIST_HOSPITAL';
export const LIST_HOSPITAL_LOADING = 'LIST_HOSPITAL_LOADING';
export const SAVE_HOSPITAL_LOADING = 'SAVE_HOSPITAL_LOADING';
export const SELECTED_HOSPITAL = 'SELECTED_HOSPITAL';

/** profiles */
export const LIST_PROFILES_LOADING = 'LIST_PROFILES_LOADING';
export const SAVE_PROFILES_LOADING = 'SAVE_PROFILES_LOADING';
export const LIST_PROFILES = 'LIST_PROFILES';
export const SELECTED_PROFILE = 'SELECTED_PROFILE';
export const SET_PROFILE_USER = 'SET_PROFILE_USER';
export const SET_PROFILE_DOCTOR = 'SET_PROFILE_DOCTOR';
export const SET_PROFILE_HOSPITAL = 'SET_PROFILE_HOSPITAL';
export const SET_PROFILE_ROLE = 'SET_PROFILE_ROLE';

export const ADD_FORM_TEXT = 'ADD_FORM_TEXT';
export const EDIT_FORM_TEXT = 'EDIT_FORM_TEXT';
export const DELETE_FORM_TEXT = 'DELETE_FORM_TEXT';
export const DETAILS_FORM_TEXT = 'DETAILS_FORM_TEXT';

/** validator text */
export const REQUIRED_FIELD = 'Este campo es obligatorio.';

/** pagination */
export const SET_PAGINATION_PAGE = 'SET_PAGINATION_PAGE';
export const SET_PAGINATION_LIMIT = 'SET_PAGINATION_LIMIT';
